name: Testing reusable workflow

on:
    workflow_dispatch:

jobs:
    jobone:
        uses: ./.github/workflows/test-reusable-workflow.yaml
        with:
            env: 'build'
    jobtwo:
        with:
            env: 'deploy'
        if: ${{ needs.jobone.outputs.test_output_one == "true" }}
        needs: jobone
        uses: ./.github/workflows/test-reusable-workflow.yaml

        # runs-on: ubuntu-latest
        # steps:
        #     - name: stepone
        #       run: echo "Running jobtwo"
