name: Testing reusable workflow

on:
    workflow_dispatch:

jobs:
    jobone:
        uses: ./.github/workflows/test-reusable-workflow.yaml
    jobtwo:
        if: ${{ needs.jobone.outputs.test_output_one == 'false' }}
        needs: jobone
        uses: ./.github/workflows/test-reusable-workflow.yaml

        # runs-on: ubuntu-latest
        # steps:
        #     - name: stepone
        #       run: echo "Running jobtwo"
