name: Testing reusable workflow

on:
    workflow_dispatch:

jobs:
    jobone:
        uses: ./.github/workflows/test-reusable-workflow.yaml
        with:
            env: 'build'
            job: 'jobone'
    jobtwo:
        if: ${{ needs.jobone.outputs.test_output_one == "true" }}
        with:
            env: 'deploy'
            job: 'jobtwo'
        needs: jobone
        uses: ./.github/workflows/test-reusable-workflow.yaml
